"""empty message

Revision ID: 1c5dfc3ebe6e
Revises: 
Create Date: 2019-08-12 23:10:23.964704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5dfc3ebe6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('plate_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('plate_number')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'year')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('english_name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('has_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=100), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('university', sa.String(length=100), nullable=True),
    sa.Column('graduation_year', sa.String(length=10), nullable=True),
    sa.Column('is_servant', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('is_child', sa.Boolean(), nullable=True),
    sa.Column('is_system_admin', sa.Boolean(), nullable=True),
    sa.Column('is_family_admin', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('father', sa.Integer(), nullable=False),
    sa.Column('mother', sa.Integer(), nullable=False),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['users.id'], ),
    sa.ForeignKeyConstraint(['father'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mother'], ['users.id'], ),
    sa.PrimaryKeyConstraint('father', 'mother', 'child')
    )
    op.create_table('meeting_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('servant_id', sa.Integer(), nullable=True),
    sa.Column('is_servant', sa.Boolean(), nullable=True),
    sa.Column('is_leader', sa.Boolean(), nullable=True),
    sa.Column('has_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['servant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'member_id')
    )
    op.create_table('meetings_service_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes_url', sa.String(length=1000), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('recording', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'date')
    )
    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('meeting_member_id', sa.Integer(), nullable=False),
    sa.Column('service_day_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('has_bible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_member_id'], ['meeting_members.id'], ),
    sa.ForeignKeyConstraint(['service_day_id'], ['meetings_service_days.id'], ),
    sa.PrimaryKeyConstraint('meeting_member_id', 'service_day_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_attendance')
    op.drop_table('meetings_service_days')
    op.drop_table('meeting_members')
    op.drop_table('families')
    op.drop_table('users')
    op.drop_table('meetings')
    op.drop_table('cars')
    # ### end Alembic commands ###
