"""empty message

Revision ID: 22c4dcd51a7c
Revises: 5ba054d03608
Create Date: 2019-08-11 12:16:28.011175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c4dcd51a7c'
down_revision = '5ba054d03608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=15), nullable=True))
        batch_op.drop_column('mobile_str')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_str', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
