"""empty message

Revision ID: 5ba054d03608
Revises: 3d5b9022b8ae
Create Date: 2019-08-11 12:16:05.231840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba054d03608'
down_revision = '3d5b9022b8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_str', sa.String(length=15), nullable=True))
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.INTEGER(), nullable=True))
        batch_op.drop_column('mobile_str')

    # ### end Alembic commands ###
