"""empty message

Revision ID: 9777ccd492dd
Revises: efcbddb40041
Create Date: 2019-08-02 18:34:55.181161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9777ccd492dd'
down_revision = 'efcbddb40041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###
