"""empty message

Revision ID: b5ff2a8685cd
Revises: 
Create Date: 2019-08-02 17:54:57.453626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ff2a8685cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('plate_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('plate_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('english_name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.Column('whatsapp', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=100), nullable=True),
    sa.Column('student', sa.Boolean(), nullable=True),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('university', sa.String(length=100), nullable=True),
    sa.Column('servant', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('child', sa.Boolean(), nullable=True),
    sa.Column('system_admin', sa.Boolean(), nullable=True),
    sa.Column('family_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('father', sa.Integer(), nullable=False),
    sa.Column('mother', sa.Integer(), nullable=False),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['users.id'], ),
    sa.ForeignKeyConstraint(['father'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mother'], ['users.id'], ),
    sa.PrimaryKeyConstraint('father', 'mother', 'child')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('families')
    op.drop_table('users')
    op.drop_table('cars')
    # ### end Alembic commands ###
