"""empty message

Revision ID: efcbddb40041
Revises: 
Create Date: 2019-08-02 18:22:19.679191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcbddb40041'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'year')
    )
    op.create_table('meeting_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('servant_id', sa.Integer(), nullable=True),
    sa.Column('is_servant', sa.Boolean(), nullable=True),
    sa.Column('is_leader', sa.Boolean(), nullable=True),
    sa.Column('has_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['servant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'member_id')
    )
    op.create_table('meetings_service_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes_url', sa.String(length=1000), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('recording', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'date')
    )
    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('meeting_member_id', sa.Integer(), nullable=False),
    sa.Column('service_day_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('has_bible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_member_id'], ['meeting_members.id'], ),
    sa.ForeignKeyConstraint(['service_day_id'], ['meetings_service_days.id'], ),
    sa.PrimaryKeyConstraint('meeting_member_id', 'service_day_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_attendance')
    op.drop_table('meetings_service_days')
    op.drop_table('meeting_members')
    op.drop_table('meetings')
    # ### end Alembic commands ###
